/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as InfoRouteImport } from './routes/$info'
import { Route as AccountRouteImport } from './routes/account'
import { Route as BestSellersRouteImport } from './routes/best-sellers'
import { Route as CheckoutRouteImport } from './routes/checkout'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as ForSalonsRouteImport } from './routes/for-salons'
import { Route as LgsProductsRouteImport } from './routes/lgs-products'
import { Route as NewArrivalsRouteImport } from './routes/new-arrivals'
import { Route as OffersRouteImport } from './routes/offers'
import { Route as WishlistRouteImport } from './routes/wishlist'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as AdminLayoutRouteImport } from './routes/admin/_layout'
import { Route as AdminCouponsRouteImport } from './routes/admin/coupons'
import { Route as AdminDashboardRouteImport } from './routes/admin/dashboard'
import { Route as AdminInstagramPostsRouteImport } from './routes/admin/instagram-posts'
import { Route as AdminLoginRouteImport } from './routes/admin/login'
import { Route as AdminProductsRouteImport } from './routes/admin/products'
import { Route as ProductSlugRouteImport } from './routes/product.$slug'
import { Route as ShopIndexRouteImport } from './routes/shop.index'
import { Route as ShopCategoryRouteImport } from './routes/shop.$category'
import { Route as AdminProductsIndexRouteImport } from './routes/admin/products.index'
import { Route as AdminProductsAddRouteImport } from './routes/admin/products.add'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const InfoRoute = InfoRouteImport.update({
  id: '/$info',
  path: '/$info',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountRoute = AccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => rootRouteImport,
} as any)
const BestSellersRoute = BestSellersRouteImport.update({
  id: '/best-sellers',
  path: '/best-sellers',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutRoute = CheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const ForSalonsRoute = ForSalonsRouteImport.update({
  id: '/for-salons',
  path: '/for-salons',
  getParentRoute: () => rootRouteImport,
} as any)
const LgsProductsRoute = LgsProductsRouteImport.update({
  id: '/lgs-products',
  path: '/lgs-products',
  getParentRoute: () => rootRouteImport,
} as any)
const NewArrivalsRoute = NewArrivalsRouteImport.update({
  id: '/new-arrivals',
  path: '/new-arrivals',
  getParentRoute: () => rootRouteImport,
} as any)
const OffersRoute = OffersRouteImport.update({
  id: '/offers',
  path: '/offers',
  getParentRoute: () => rootRouteImport,
} as any)
const WishlistRoute = WishlistRouteImport.update({
  id: '/wishlist',
  path: '/wishlist',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminLayoutRoute = AdminLayoutRouteImport.update({
  id: '/admin/_layout',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminCouponsRoute = AdminCouponsRouteImport.update({
  id: '/admin/coupons',
  path: '/admin/coupons',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminDashboardRoute = AdminDashboardRouteImport.update({
  id: '/admin/dashboard',
  path: '/admin/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminInstagramPostsRoute = AdminInstagramPostsRouteImport.update({
  id: '/admin/instagram-posts',
  path: '/admin/instagram-posts',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/admin/login',
  path: '/admin/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminProductsRoute = AdminProductsRouteImport.update({
  id: '/admin/products',
  path: '/admin/products',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductSlugRoute = ProductSlugRouteImport.update({
  id: '/product/$slug',
  path: '/product/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ShopIndexRoute = ShopIndexRouteImport.update({
  id: '/shop/',
  path: '/shop/',
  getParentRoute: () => rootRouteImport,
} as any)
const ShopCategoryRoute = ShopCategoryRouteImport.update({
  id: '/shop/$category',
  path: '/shop/$category',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminProductsIndexRoute = AdminProductsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminProductsRoute,
} as any)
const AdminProductsAddRoute = AdminProductsAddRouteImport.update({
  id: '/add',
  path: '/add',
  getParentRoute: () => AdminProductsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$info': typeof InfoRoute
  '/account': typeof AccountRoute
  '/best-sellers': typeof BestSellersRoute
  '/checkout': typeof CheckoutRoute
  '/contact': typeof ContactRoute
  '/for-salons': typeof ForSalonsRoute
  '/lgs-products': typeof LgsProductsRoute
  '/new-arrivals': typeof NewArrivalsRoute
  '/offers': typeof OffersRoute
  '/wishlist': typeof WishlistRoute
  '/admin': typeof AdminLayoutRoute
  '/admin/coupons': typeof AdminCouponsRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/instagram-posts': typeof AdminInstagramPostsRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/products': typeof AdminProductsRouteWithChildren
  '/product/$slug': typeof ProductSlugRoute
  '/shop/$category': typeof ShopCategoryRoute
  '/admin/': typeof AdminIndexRoute
  '/shop/': typeof ShopIndexRoute
  '/admin/products/add': typeof AdminProductsAddRoute
  '/admin/products/': typeof AdminProductsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$info': typeof InfoRoute
  '/account': typeof AccountRoute
  '/best-sellers': typeof BestSellersRoute
  '/checkout': typeof CheckoutRoute
  '/contact': typeof ContactRoute
  '/for-salons': typeof ForSalonsRoute
  '/lgs-products': typeof LgsProductsRoute
  '/new-arrivals': typeof NewArrivalsRoute
  '/offers': typeof OffersRoute
  '/wishlist': typeof WishlistRoute
  '/admin': typeof AdminIndexRoute
  '/admin/coupons': typeof AdminCouponsRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/instagram-posts': typeof AdminInstagramPostsRoute
  '/admin/login': typeof AdminLoginRoute
  '/product/$slug': typeof ProductSlugRoute
  '/shop/$category': typeof ShopCategoryRoute
  '/shop': typeof ShopIndexRoute
  '/admin/products/add': typeof AdminProductsAddRoute
  '/admin/products': typeof AdminProductsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$info': typeof InfoRoute
  '/account': typeof AccountRoute
  '/best-sellers': typeof BestSellersRoute
  '/checkout': typeof CheckoutRoute
  '/contact': typeof ContactRoute
  '/for-salons': typeof ForSalonsRoute
  '/lgs-products': typeof LgsProductsRoute
  '/new-arrivals': typeof NewArrivalsRoute
  '/offers': typeof OffersRoute
  '/wishlist': typeof WishlistRoute
  '/admin/_layout': typeof AdminLayoutRoute
  '/admin/coupons': typeof AdminCouponsRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/instagram-posts': typeof AdminInstagramPostsRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/products': typeof AdminProductsRouteWithChildren
  '/product/$slug': typeof ProductSlugRoute
  '/shop/$category': typeof ShopCategoryRoute
  '/admin/': typeof AdminIndexRoute
  '/shop/': typeof ShopIndexRoute
  '/admin/products/add': typeof AdminProductsAddRoute
  '/admin/products/': typeof AdminProductsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$info'
    | '/account'
    | '/best-sellers'
    | '/checkout'
    | '/contact'
    | '/for-salons'
    | '/lgs-products'
    | '/new-arrivals'
    | '/offers'
    | '/wishlist'
    | '/admin'
    | '/admin/coupons'
    | '/admin/dashboard'
    | '/admin/instagram-posts'
    | '/admin/login'
    | '/admin/products'
    | '/product/$slug'
    | '/shop/$category'
    | '/admin/'
    | '/shop/'
    | '/admin/products/add'
    | '/admin/products/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/$info'
    | '/account'
    | '/best-sellers'
    | '/checkout'
    | '/contact'
    | '/for-salons'
    | '/lgs-products'
    | '/new-arrivals'
    | '/offers'
    | '/wishlist'
    | '/admin'
    | '/admin/coupons'
    | '/admin/dashboard'
    | '/admin/instagram-posts'
    | '/admin/login'
    | '/product/$slug'
    | '/shop/$category'
    | '/shop'
    | '/admin/products/add'
    | '/admin/products'
  id:
    | '__root__'
    | '/'
    | '/$info'
    | '/account'
    | '/best-sellers'
    | '/checkout'
    | '/contact'
    | '/for-salons'
    | '/lgs-products'
    | '/new-arrivals'
    | '/offers'
    | '/wishlist'
    | '/admin/_layout'
    | '/admin/coupons'
    | '/admin/dashboard'
    | '/admin/instagram-posts'
    | '/admin/login'
    | '/admin/products'
    | '/product/$slug'
    | '/shop/$category'
    | '/admin/'
    | '/shop/'
    | '/admin/products/add'
    | '/admin/products/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  InfoRoute: typeof InfoRoute
  AccountRoute: typeof AccountRoute
  BestSellersRoute: typeof BestSellersRoute
  CheckoutRoute: typeof CheckoutRoute
  ContactRoute: typeof ContactRoute
  ForSalonsRoute: typeof ForSalonsRoute
  LgsProductsRoute: typeof LgsProductsRoute
  NewArrivalsRoute: typeof NewArrivalsRoute
  OffersRoute: typeof OffersRoute
  WishlistRoute: typeof WishlistRoute
  AdminLayoutRoute: typeof AdminLayoutRoute
  AdminCouponsRoute: typeof AdminCouponsRoute
  AdminDashboardRoute: typeof AdminDashboardRoute
  AdminInstagramPostsRoute: typeof AdminInstagramPostsRoute
  AdminLoginRoute: typeof AdminLoginRoute
  AdminProductsRoute: typeof AdminProductsRouteWithChildren
  ProductSlugRoute: typeof ProductSlugRoute
  ShopCategoryRoute: typeof ShopCategoryRoute
  AdminIndexRoute: typeof AdminIndexRoute
  ShopIndexRoute: typeof ShopIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$info': {
      id: '/$info'
      path: '/$info'
      fullPath: '/$info'
      preLoaderRoute: typeof InfoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account': {
      id: '/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AccountRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/best-sellers': {
      id: '/best-sellers'
      path: '/best-sellers'
      fullPath: '/best-sellers'
      preLoaderRoute: typeof BestSellersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout': {
      id: '/checkout'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof CheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/for-salons': {
      id: '/for-salons'
      path: '/for-salons'
      fullPath: '/for-salons'
      preLoaderRoute: typeof ForSalonsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lgs-products': {
      id: '/lgs-products'
      path: '/lgs-products'
      fullPath: '/lgs-products'
      preLoaderRoute: typeof LgsProductsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/new-arrivals': {
      id: '/new-arrivals'
      path: '/new-arrivals'
      fullPath: '/new-arrivals'
      preLoaderRoute: typeof NewArrivalsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/offers': {
      id: '/offers'
      path: '/offers'
      fullPath: '/offers'
      preLoaderRoute: typeof OffersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/wishlist': {
      id: '/wishlist'
      path: '/wishlist'
      fullPath: '/wishlist'
      preLoaderRoute: typeof WishlistRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/_layout': {
      id: '/admin/_layout'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminLayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/coupons': {
      id: '/admin/coupons'
      path: '/admin/coupons'
      fullPath: '/admin/coupons'
      preLoaderRoute: typeof AdminCouponsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/dashboard': {
      id: '/admin/dashboard'
      path: '/admin/dashboard'
      fullPath: '/admin/dashboard'
      preLoaderRoute: typeof AdminDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/instagram-posts': {
      id: '/admin/instagram-posts'
      path: '/admin/instagram-posts'
      fullPath: '/admin/instagram-posts'
      preLoaderRoute: typeof AdminInstagramPostsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/login': {
      id: '/admin/login'
      path: '/admin/login'
      fullPath: '/admin/login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/products': {
      id: '/admin/products'
      path: '/admin/products'
      fullPath: '/admin/products'
      preLoaderRoute: typeof AdminProductsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/product/$slug': {
      id: '/product/$slug'
      path: '/product/$slug'
      fullPath: '/product/$slug'
      preLoaderRoute: typeof ProductSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shop/': {
      id: '/shop/'
      path: '/shop'
      fullPath: '/shop/'
      preLoaderRoute: typeof ShopIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shop/$category': {
      id: '/shop/$category'
      path: '/shop/$category'
      fullPath: '/shop/$category'
      preLoaderRoute: typeof ShopCategoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/products/': {
      id: '/admin/products/'
      path: '/'
      fullPath: '/admin/products/'
      preLoaderRoute: typeof AdminProductsIndexRouteImport
      parentRoute: typeof AdminProductsRoute
    }
    '/admin/products/add': {
      id: '/admin/products/add'
      path: '/add'
      fullPath: '/admin/products/add'
      preLoaderRoute: typeof AdminProductsAddRouteImport
      parentRoute: typeof AdminProductsRoute
    }
  }
}

interface AdminProductsRouteChildren {
  AdminProductsAddRoute: typeof AdminProductsAddRoute
  AdminProductsIndexRoute: typeof AdminProductsIndexRoute
}

const AdminProductsRouteChildren: AdminProductsRouteChildren = {
  AdminProductsAddRoute: AdminProductsAddRoute,
  AdminProductsIndexRoute: AdminProductsIndexRoute,
}

const AdminProductsRouteWithChildren = AdminProductsRoute._addFileChildren(
  AdminProductsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  InfoRoute: InfoRoute,
  AccountRoute: AccountRoute,
  BestSellersRoute: BestSellersRoute,
  CheckoutRoute: CheckoutRoute,
  ContactRoute: ContactRoute,
  ForSalonsRoute: ForSalonsRoute,
  LgsProductsRoute: LgsProductsRoute,
  NewArrivalsRoute: NewArrivalsRoute,
  OffersRoute: OffersRoute,
  WishlistRoute: WishlistRoute,
  AdminLayoutRoute: AdminLayoutRoute,
  AdminCouponsRoute: AdminCouponsRoute,
  AdminDashboardRoute: AdminDashboardRoute,
  AdminInstagramPostsRoute: AdminInstagramPostsRoute,
  AdminLoginRoute: AdminLoginRoute,
  AdminProductsRoute: AdminProductsRouteWithChildren,
  ProductSlugRoute: ProductSlugRoute,
  ShopCategoryRoute: ShopCategoryRoute,
  AdminIndexRoute: AdminIndexRoute,
  ShopIndexRoute: ShopIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
